### ISSUE TITLE
Correção animação na página de Login.

### ISSUE THREAD

**Issue by fabriciodcm** [fabriciodcm/ChemQuiz#1]
Correção animação na página de Login . Foi utilizado o pacote Lottie para realizar a animação.
Material de apoio utilizado para fazer a tela de Login :
https://medium.com/@thallisonrlima/como-fazer-a-tela-de-login-mais-bonita-do-mundo-com-xamarin-forms-f74524c3a508

**Comment by lyncolnms** [comment]
Se for utilizar a última versão do Lottie(3.1.0) e/ou a última versão do XF.Material(1.6.3), é necessário atualizar para o Android 10.

**Comment by fabriciodcm** [comment]
Problema resolvido.
